### ISSUE TITLE
UniswapV2Pair.spec.ts mint

### ISSUE THREAD

**Issue by duelinggalois** [Ammalgam-Protocol/v2-core#3]
rewrite tests using solidity running in Foundry.

Test descriptions:

1. mint

```
  it('mint', async () => {
    const token0Amount = expandTo18Decimals(1) // 1 000 000 000 000 000 000
    const token1Amount = expandTo18Decimals(4)
    await token0.transfer(pair.address, token0Amount)
    await token1.transfer(pair.address, token1Amount) // x , y: 1 *10 ^18 * 4 * 10 ^18

    const expectedLiquidity = expandTo18Decimals(2)
    await expect(pair.mint(wallet.address, overrides))
      .to.emit(pair, 'Transfer')
      .withArgs(AddressZero, AddressZero, MINIMUM_LIQUIDITY)
      .to.emit(pair, 'Transfer')
      .withArgs(AddressZero, wallet.address, expectedLiquidity.sub(MINIMUM_LIQUIDITY))
      .to.emit(pair, 'Sync')
      .withArgs(token0Amount, token1Amount)
      .to.emit(pair, 'Mint')
      .withArgs(wallet.address, token0Amount, token1Amount)

    expect(await pair.totalSupply()).to.eq(expectedLiquidity)
    expect(await pair.balanceOf(wallet.address)).to.eq(expectedLiquidity.sub(MINIMUM_LIQUIDITY))
    expect(await token0.balanceOf(pair.address)).to.eq(token0Amount)
    expect(await token1.balanceOf(pair.address)).to.eq(token1Amount)
    const reserves = await pair.getReserves()
    expect(reserves[0]).to.eq(token0Amount)
    expect(reserves[1]).to.eq(token1Amount)
  })
  ```

**Comment by duelinggalois** [comment]
2

**Comment by cirethic** [comment]
Added some practical tests in feature/3-uniswapv2pair.ts-mint-using-forge-wip/v2-core/test/feature-3-mint.t.sol 

Encountered a problem using new version of foundry test. 
   import "forge-std/Test.sol";  // raise err: failed to resolve versions

if it's  
   import "ds-test/test.sol"; 
it would work.


$forge test

```
[⠃] Compiling...2022-05-10T16:58:05.702665Z ERROR ethers_solc::resolver: failed to resolve versions
[⠊] Compiling...
Error:
   0: Discovered incompatible solidity versions in following
      : test/feature-3-mint.t.sol (>=0.5.0 < 0.8.11) imports:
          lib/forge-std/src/Test.sol (>=0.6.0 <0.9.0)
          contracts/UniswapV2Pair.sol (=0.5.16)
          lib/forge-std/src/Vm.sol (>=0.6.0)
          lib/forge-std/lib/ds-test/src/test.sol (>=0.5.0)
          lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
          lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
          contracts/interfaces/IUniswapV2Pair.sol (>=0.5.0)
          contracts/UniswapV2ERC20.sol (=0.5.16)
          contracts/libraries/Math.sol (=0.5.16)
          contracts/libraries/UQ112x112.sol (=0.5.16)
          contracts/interfaces/IERC20.sol (>=0.5.0)
          contracts/interfaces/IUniswapV2Factory.sol (>=0.5.0)
          contracts/interfaces/IUniswapV2Callee.sol (>=0.5.0)
          contracts/interfaces/IUniswapV2ERC20.sol (>=0.5.0)
          contracts/libraries/SafeMath.sol (=0.5.16)

Location:
   cli/src/compile.rs:99

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```

**Comment by cirethic** [comment]
Trying to resolve the issue:

[FAIL. Reason: Log != expected log] testMintCase1() (gas: 241424)
Traces:
  [238624] UniswapV2PairTest::testMintCase1()
    ├─ [29822] StubERC20::transfer(UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997], 1000000000000000000)
    │   ├─ emit Transfer(from: UniswapV2PairTest: [0xb4c79dab8f259c7aee6e5b2aa729821864227e84], to: UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997], value: 1000000000000000000)
    │   └─ ← true
    ├─ [29822] StubERC20::transfer(UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997], 4000000000000000000)
    │   ├─ emit Transfer(from: UniswapV2PairTest: [0xb4c79dab8f259c7aee6e5b2aa729821864227e84], to: UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997], value: 4000000000000000000)
    │   └─ ← true
    ├─ [153583] UniswapV2Pair::mint(UniswapV2PairTest: [0xb4c79dab8f259c7aee6e5b2aa729821864227e84])
    │   ├─ [562] StubERC20::balanceOf(UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997]) [staticcall]
    │   │   └─ ← 1000000000000000000
    │   ├─ [562] StubERC20::balanceOf(UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997]) [staticcall]
    │   │   └─ ← 4000000000000000000
    │   ├─ [2327] UniswapV2Factory::feeTo() [staticcall]
    │   │   └─ ← UniswapV2PairTest: [0xb4c79dab8f259c7aee6e5b2aa729821864227e84]
    │   ├─ emit Transfer(from: 0x0000000000000000000000000000000000000000, to: 0x0000000000000000000000000000000000000000, value: 1000)
    │   ├─ emit Transfer(from: 0x0000000000000000000000000000000000000000, to: UniswapV2PairTest: [0xb4c79dab8f259c7aee6e5b2aa729821864227e84], value: 1999999999999999000)
    │   ├─ emit Sync(reserve0: 1000000000000000000, reserve1: 4000000000000000000)
    │   ├─ emit Mint(sender: UniswapV2PairTest: [0xb4c79dab8f259c7aee6e5b2aa729821864227e84], amount0: 1000000000000000000, amount1: 4000000000000000000)
    │   └─ ← 1999999999999999000
    ├─ [0] VM::expectEmit(true, true, true, true)
    │   └─ ← ()
    ├─ emit Transfer(from: 0x0000000000000000000000000000000000000000, to: 0x0000000000000000000000000000000000000000, value: 9)
    ├─ [429] UniswapV2Pair::totalSupply() [staticcall]
    │   └─ ← 2000000000000000000
    ├─ [562] StubERC20::balanceOf(UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997]) [staticcall]
    │   └─ ← 1000000000000000000
    ├─ [562] StubERC20::balanceOf(UniswapV2Pair: [0x91dc51c447ed57b591e18f80e4b984e5bf641997]) [staticcall]
    │   └─ ← 4000000000000000000
    ├─ [526] UniswapV2Pair::getReserves() [staticcall]
    │   └─ ← 1000000000000000000, 4000000000000000000, 1
    └─ ← ()

Test result: FAILED. 0 passed; 1 failed; finished in 2.46ms

Failed tests:
[FAIL. Reason: Log != expected log] testMintCase1() (gas: 241424)



code from feature-3-mint.t.sol
```
      vm.expectEmit(true, true, true, true);
      emit Transfer(address(0),address(0),  MINIMUM_LIQUIDITY);

```

**Comment by cirethic** [comment]
solution found: 
There are 3 issue caused Log != expected log:

1. call mint function after emit 

```
      vm.expectEmit(true, false, false, true);
      emit Mint(address(this), token0Amount, token1Amount);

      **pair.mint(address(this));**
```

2. make sure the expectEmit topics match indexed parameters 
```
      vm.expectEmit(true, false, false, true);

```

3.  make sure the values in emit function is correct 
```
  emit Transfer(address(0),address(0),  MINIMUM_LIQUIDITY);
```
